### ISSUE TITLE
Anonymous Walkin Throws error while trying add Walkin when no-slot available

### ISSUE THREAD

**Issue by yobnytech** [yobnytech/queueone_issues_tracker#128]
Internal Server Error: /qone/v1.0/queue/anonymous/walkin/
Traceback (most recent call last):
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/rest_framework/decorators.py", line 54, in handler
    return func(*args, **kwargs)
  File "./queueone/catalogue/queueapi.py", line 1403, in join_anonymous_customer
    logger.error("Anonymous user addition failed for queue {}, Error {}".format(bookable_app_product.product.title, "No slots available"))

**Comment by yobnytech** [comment]
Fixed and closed
