### ISSUE TITLE
Walkin Addtion Fails Randomly 

### ISSUE THREAD

**Issue by yobnytech** [yobnytech/queueone_issues_tracker#129]
db.query(q)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry 'xxxxxxxx@mail.com' for key 'username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./queueone/catalogue/queueapi.py", line 1501, in join_walkin_customer
    username=user_email
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/contrib/auth/models.py", line 150, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/contrib/auth/models.py", line 144, in _create_user
    user.save(using=self._db)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/db/models/base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/db/models/base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1128, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1285, in execute_sql
    cursor.execute(sql, params)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/graphene_django/debug/sql/tracking.py", line 155, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/graphene_django/debug/sql/tracking.py", line 101, in _record
    return method(sql, params)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute

**Comment by yobnytech** [comment]
Fixed
