### ISSUE TITLE
Partner web : new employee creation does not work

### ISSUE THREAD

**Issue by saurabh-vyas** [yobnytech/queueone_issues_tracker#22]
Tried creating a new employee (as manager) in Apollo, new user was not created.
No error is shown.

**Comment by yobnytech** [comment]
It works but due to exception, it is not showing up immediately

 msecs (HTTP/1.1 200) 7 headers in 365 bytes (2 switches on core 0)
/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField FirebaseAuth.date_authenticated received a naive datetime (2019-08-06 19:50:20.742379) while time zone support is active.
  RuntimeWarning)
Internal Server Error: /qone/v1.0/store/create/staff/45/
Traceback (most recent call last):
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/qonemiddleware/venv/lib/python3.6/site-packages/rest_framework/decorators.py", line 54, in handler
    return func(*args, **kwargs)
  File "./queueone/stores/api.py", line 267, in create_store_staff
    sender = QueueIntermediate,
NameError: name 'QueueIntermediate' is not defined

**Comment by qonelead** [comment]
Ok, so this works fine. But had to do a hard refresh for the newly created employee (manager role) to appear.
Tried this in Yobny test partner.

This can be closed (hard refresh is not critical for this to keep it open).
